all:
	make -C tests
	make -C example_program
	@echo "***********************************"
	@echo "Everything compiled successfully"
	@echo "***********************************"

clean:
	make -C tests clean
	make -C example_program clean
